# Generated by Django 3.2.9 on 2021-12-03 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name project')),
                ('description', models.CharField(max_length=220, verbose_name='Description')),
                ('full_descrip', models.TextField(null=True, verbose_name='Full description')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=2000)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('type_of_exercise', models.CharField(choices=[('FE', 'Feature'), ('BA', 'Bag')], default='FE', max_length=2, verbose_name='Type exercise')),
                ('task_of_priority', models.CharField(choices=[('NO', 'Normal'), ('HI', 'High'), ('UR', 'Urgent')], default='NO', max_length=2, verbose_name='Task of priority')),
                ('time', models.TimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProManager.project')),
            ],
        ),
    ]
